version: "3.2"
services:
  zookeeper:
    build: ./zookeeper
    container_name: zookeeper
    command:
      - "start-foreground"
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.24.18.44:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=customer1:3:1,audit1:3:1
      - JMX_PORT=9999

  kafka-jmx-exporter:
    build: ./prometheus-jmx-exporter
    container_name: jmx-exporter
    ports:
      - "8080:8080"
    links:
      - kafka
    environment:
      - JMX_PORT=9999
      - JMX_HOST=kafka
      - HTTP_PORT=8080
      - JMX_EXPORTER_CONFIG_FILE=kafka.yml

  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    links:
      - kafka
    ports:
      - 9308:9308
    command:
      - '--kafka.server=172.24.18.44:9092'

  prometheus:
    container_name: prometheus
    ports:
      - 9090:9090/tcp
    image: prom/prometheus
    volumes:
      - ./mount/prometheus:/etc/prometheus
    links:
      - kafka-jmx-exporter

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000/tcp
    links:
      - prometheus
    volumes:
      - ./mount/grafana/lib:/var/lib/grafana
